packages:
  github.com/blogem/eod-scheduler/repositories:
    interfaces:
      TeamRepository:
        config:
          dir: "repositories/mocks"
          filename: "mock_TeamRepository.go"
      WorkingHoursRepository:
        config:
          dir: "repositories/mocks"
          filename: "mock_WorkingHoursRepository.go"
      ScheduleRepository:
        config:
          dir: "repositories/mocks"
          filename: "mock_ScheduleRepository.go"
