// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/blogem/eod-scheduler/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockScheduleRepository is an autogenerated mock type for the ScheduleRepository type
type MockScheduleRepository struct {
	mock.Mock
}

type MockScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleRepository) EXPECT() *MockScheduleRepository_Expecter {
	return &MockScheduleRepository_Expecter{mock: &_m.Mock}
}

// CountByTeamMember provides a mock function with given fields: teamMemberID
func (_m *MockScheduleRepository) CountByTeamMember(teamMemberID int) (int, error) {
	ret := _m.Called(teamMemberID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTeamMember")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(teamMemberID)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(teamMemberID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(teamMemberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_CountByTeamMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTeamMember'
type MockScheduleRepository_CountByTeamMember_Call struct {
	*mock.Call
}

// CountByTeamMember is a helper method to define mock.On call
//   - teamMemberID int
func (_e *MockScheduleRepository_Expecter) CountByTeamMember(teamMemberID interface{}) *MockScheduleRepository_CountByTeamMember_Call {
	return &MockScheduleRepository_CountByTeamMember_Call{Call: _e.mock.On("CountByTeamMember", teamMemberID)}
}

func (_c *MockScheduleRepository_CountByTeamMember_Call) Run(run func(teamMemberID int)) *MockScheduleRepository_CountByTeamMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockScheduleRepository_CountByTeamMember_Call) Return(_a0 int, _a1 error) *MockScheduleRepository_CountByTeamMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_CountByTeamMember_Call) RunAndReturn(run func(int) (int, error)) *MockScheduleRepository_CountByTeamMember_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: entry
func (_m *MockScheduleRepository) Create(entry *models.ScheduleEntry) error {
	ret := _m.Called(entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ScheduleEntry) error); ok {
		r0 = rf(entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScheduleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockScheduleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - entry *models.ScheduleEntry
func (_e *MockScheduleRepository_Expecter) Create(entry interface{}) *MockScheduleRepository_Create_Call {
	return &MockScheduleRepository_Create_Call{Call: _e.mock.On("Create", entry)}
}

func (_c *MockScheduleRepository_Create_Call) Run(run func(entry *models.ScheduleEntry)) *MockScheduleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.ScheduleEntry))
	})
	return _c
}

func (_c *MockScheduleRepository_Create_Call) Return(_a0 error) *MockScheduleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScheduleRepository_Create_Call) RunAndReturn(run func(*models.ScheduleEntry) error) *MockScheduleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockScheduleRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScheduleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockScheduleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockScheduleRepository_Expecter) Delete(id interface{}) *MockScheduleRepository_Delete_Call {
	return &MockScheduleRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockScheduleRepository_Delete_Call) Run(run func(id int)) *MockScheduleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockScheduleRepository_Delete_Call) Return(_a0 error) *MockScheduleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScheduleRepository_Delete_Call) RunAndReturn(run func(int) error) *MockScheduleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByDateRange provides a mock function with given fields: from, to
func (_m *MockScheduleRepository) DeleteByDateRange(from time.Time, to time.Time) error {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByDateRange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) error); ok {
		r0 = rf(from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScheduleRepository_DeleteByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByDateRange'
type MockScheduleRepository_DeleteByDateRange_Call struct {
	*mock.Call
}

// DeleteByDateRange is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
func (_e *MockScheduleRepository_Expecter) DeleteByDateRange(from interface{}, to interface{}) *MockScheduleRepository_DeleteByDateRange_Call {
	return &MockScheduleRepository_DeleteByDateRange_Call{Call: _e.mock.On("DeleteByDateRange", from, to)}
}

func (_c *MockScheduleRepository_DeleteByDateRange_Call) Run(run func(from time.Time, to time.Time)) *MockScheduleRepository_DeleteByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockScheduleRepository_DeleteByDateRange_Call) Return(_a0 error) *MockScheduleRepository_DeleteByDateRange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScheduleRepository_DeleteByDateRange_Call) RunAndReturn(run func(time.Time, time.Time) error) *MockScheduleRepository_DeleteByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetByDate provides a mock function with given fields: date
func (_m *MockScheduleRepository) GetByDate(date time.Time) ([]models.ScheduleEntry, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for GetByDate")
	}

	var r0 []models.ScheduleEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) ([]models.ScheduleEntry, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(time.Time) []models.ScheduleEntry); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ScheduleEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_GetByDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByDate'
type MockScheduleRepository_GetByDate_Call struct {
	*mock.Call
}

// GetByDate is a helper method to define mock.On call
//   - date time.Time
func (_e *MockScheduleRepository_Expecter) GetByDate(date interface{}) *MockScheduleRepository_GetByDate_Call {
	return &MockScheduleRepository_GetByDate_Call{Call: _e.mock.On("GetByDate", date)}
}

func (_c *MockScheduleRepository_GetByDate_Call) Run(run func(date time.Time)) *MockScheduleRepository_GetByDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MockScheduleRepository_GetByDate_Call) Return(_a0 []models.ScheduleEntry, _a1 error) *MockScheduleRepository_GetByDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_GetByDate_Call) RunAndReturn(run func(time.Time) ([]models.ScheduleEntry, error)) *MockScheduleRepository_GetByDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByDateRange provides a mock function with given fields: from, to
func (_m *MockScheduleRepository) GetByDateRange(from time.Time, to time.Time) ([]models.ScheduleEntry, error) {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetByDateRange")
	}

	var r0 []models.ScheduleEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) ([]models.ScheduleEntry, error)); ok {
		return rf(from, to)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) []models.ScheduleEntry); ok {
		r0 = rf(from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ScheduleEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_GetByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByDateRange'
type MockScheduleRepository_GetByDateRange_Call struct {
	*mock.Call
}

// GetByDateRange is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
func (_e *MockScheduleRepository_Expecter) GetByDateRange(from interface{}, to interface{}) *MockScheduleRepository_GetByDateRange_Call {
	return &MockScheduleRepository_GetByDateRange_Call{Call: _e.mock.On("GetByDateRange", from, to)}
}

func (_c *MockScheduleRepository_GetByDateRange_Call) Run(run func(from time.Time, to time.Time)) *MockScheduleRepository_GetByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time), args[1].(time.Time))
	})
	return _c
}

func (_c *MockScheduleRepository_GetByDateRange_Call) Return(_a0 []models.ScheduleEntry, _a1 error) *MockScheduleRepository_GetByDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_GetByDateRange_Call) RunAndReturn(run func(time.Time, time.Time) ([]models.ScheduleEntry, error)) *MockScheduleRepository_GetByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockScheduleRepository) GetByID(id int) (*models.ScheduleEntry, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.ScheduleEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.ScheduleEntry, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.ScheduleEntry); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ScheduleEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockScheduleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *MockScheduleRepository_Expecter) GetByID(id interface{}) *MockScheduleRepository_GetByID_Call {
	return &MockScheduleRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockScheduleRepository_GetByID_Call) Run(run func(id int)) *MockScheduleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockScheduleRepository_GetByID_Call) Return(_a0 *models.ScheduleEntry, _a1 error) *MockScheduleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_GetByID_Call) RunAndReturn(run func(int) (*models.ScheduleEntry, error)) *MockScheduleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function with no fields
func (_m *MockScheduleRepository) GetState() (*models.ScheduleState, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 *models.ScheduleState
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.ScheduleState, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.ScheduleState); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ScheduleState)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockScheduleRepository_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *MockScheduleRepository_Expecter) GetState() *MockScheduleRepository_GetState_Call {
	return &MockScheduleRepository_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *MockScheduleRepository_GetState_Call) Run(run func()) *MockScheduleRepository_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScheduleRepository_GetState_Call) Return(_a0 *models.ScheduleState, _a1 error) *MockScheduleRepository_GetState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_GetState_Call) RunAndReturn(run func() (*models.ScheduleState, error)) *MockScheduleRepository_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// HasFutureEntries provides a mock function with given fields: teamMemberID
func (_m *MockScheduleRepository) HasFutureEntries(teamMemberID int) (bool, error) {
	ret := _m.Called(teamMemberID)

	if len(ret) == 0 {
		panic("no return value specified for HasFutureEntries")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (bool, error)); ok {
		return rf(teamMemberID)
	}
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(teamMemberID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(teamMemberID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_HasFutureEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFutureEntries'
type MockScheduleRepository_HasFutureEntries_Call struct {
	*mock.Call
}

// HasFutureEntries is a helper method to define mock.On call
//   - teamMemberID int
func (_e *MockScheduleRepository_Expecter) HasFutureEntries(teamMemberID interface{}) *MockScheduleRepository_HasFutureEntries_Call {
	return &MockScheduleRepository_HasFutureEntries_Call{Call: _e.mock.On("HasFutureEntries", teamMemberID)}
}

func (_c *MockScheduleRepository_HasFutureEntries_Call) Run(run func(teamMemberID int)) *MockScheduleRepository_HasFutureEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockScheduleRepository_HasFutureEntries_Call) Return(_a0 bool, _a1 error) *MockScheduleRepository_HasFutureEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_HasFutureEntries_Call) RunAndReturn(run func(int) (bool, error)) *MockScheduleRepository_HasFutureEntries_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: entry
func (_m *MockScheduleRepository) Update(entry *models.ScheduleEntry) error {
	ret := _m.Called(entry)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ScheduleEntry) error); ok {
		r0 = rf(entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScheduleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockScheduleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - entry *models.ScheduleEntry
func (_e *MockScheduleRepository_Expecter) Update(entry interface{}) *MockScheduleRepository_Update_Call {
	return &MockScheduleRepository_Update_Call{Call: _e.mock.On("Update", entry)}
}

func (_c *MockScheduleRepository_Update_Call) Run(run func(entry *models.ScheduleEntry)) *MockScheduleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.ScheduleEntry))
	})
	return _c
}

func (_c *MockScheduleRepository_Update_Call) Return(_a0 error) *MockScheduleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScheduleRepository_Update_Call) RunAndReturn(run func(*models.ScheduleEntry) error) *MockScheduleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateState provides a mock function with given fields: state
func (_m *MockScheduleRepository) UpdateState(state *models.ScheduleState) error {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ScheduleState) error); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScheduleRepository_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type MockScheduleRepository_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - state *models.ScheduleState
func (_e *MockScheduleRepository_Expecter) UpdateState(state interface{}) *MockScheduleRepository_UpdateState_Call {
	return &MockScheduleRepository_UpdateState_Call{Call: _e.mock.On("UpdateState", state)}
}

func (_c *MockScheduleRepository_UpdateState_Call) Run(run func(state *models.ScheduleState)) *MockScheduleRepository_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.ScheduleState))
	})
	return _c
}

func (_c *MockScheduleRepository_UpdateState_Call) Return(_a0 error) *MockScheduleRepository_UpdateState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScheduleRepository_UpdateState_Call) RunAndReturn(run func(*models.ScheduleState) error) *MockScheduleRepository_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScheduleRepository creates a new instance of MockScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleRepository {
	mock := &MockScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
