// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/blogem/eod-scheduler/models"
	mock "github.com/stretchr/testify/mock"
)

// MockWorkingHoursRepository is an autogenerated mock type for the WorkingHoursRepository type
type MockWorkingHoursRepository struct {
	mock.Mock
}

type MockWorkingHoursRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkingHoursRepository) EXPECT() *MockWorkingHoursRepository_Expecter {
	return &MockWorkingHoursRepository_Expecter{mock: &_m.Mock}
}

// GetActiveDays provides a mock function with no fields
func (_m *MockWorkingHoursRepository) GetActiveDays() ([]models.WorkingHours, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveDays")
	}

	var r0 []models.WorkingHours
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.WorkingHours, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.WorkingHours); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WorkingHours)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkingHoursRepository_GetActiveDays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveDays'
type MockWorkingHoursRepository_GetActiveDays_Call struct {
	*mock.Call
}

// GetActiveDays is a helper method to define mock.On call
func (_e *MockWorkingHoursRepository_Expecter) GetActiveDays() *MockWorkingHoursRepository_GetActiveDays_Call {
	return &MockWorkingHoursRepository_GetActiveDays_Call{Call: _e.mock.On("GetActiveDays")}
}

func (_c *MockWorkingHoursRepository_GetActiveDays_Call) Run(run func()) *MockWorkingHoursRepository_GetActiveDays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWorkingHoursRepository_GetActiveDays_Call) Return(_a0 []models.WorkingHours, _a1 error) *MockWorkingHoursRepository_GetActiveDays_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkingHoursRepository_GetActiveDays_Call) RunAndReturn(run func() ([]models.WorkingHours, error)) *MockWorkingHoursRepository_GetActiveDays_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockWorkingHoursRepository) GetAll() ([]models.WorkingHours, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.WorkingHours
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.WorkingHours, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.WorkingHours); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WorkingHours)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkingHoursRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockWorkingHoursRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockWorkingHoursRepository_Expecter) GetAll() *MockWorkingHoursRepository_GetAll_Call {
	return &MockWorkingHoursRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockWorkingHoursRepository_GetAll_Call) Run(run func()) *MockWorkingHoursRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWorkingHoursRepository_GetAll_Call) Return(_a0 []models.WorkingHours, _a1 error) *MockWorkingHoursRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkingHoursRepository_GetAll_Call) RunAndReturn(run func() ([]models.WorkingHours, error)) *MockWorkingHoursRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByDay provides a mock function with given fields: dayOfWeek
func (_m *MockWorkingHoursRepository) GetByDay(dayOfWeek int) (*models.WorkingHours, error) {
	ret := _m.Called(dayOfWeek)

	if len(ret) == 0 {
		panic("no return value specified for GetByDay")
	}

	var r0 *models.WorkingHours
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.WorkingHours, error)); ok {
		return rf(dayOfWeek)
	}
	if rf, ok := ret.Get(0).(func(int) *models.WorkingHours); ok {
		r0 = rf(dayOfWeek)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WorkingHours)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(dayOfWeek)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkingHoursRepository_GetByDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByDay'
type MockWorkingHoursRepository_GetByDay_Call struct {
	*mock.Call
}

// GetByDay is a helper method to define mock.On call
//   - dayOfWeek int
func (_e *MockWorkingHoursRepository_Expecter) GetByDay(dayOfWeek interface{}) *MockWorkingHoursRepository_GetByDay_Call {
	return &MockWorkingHoursRepository_GetByDay_Call{Call: _e.mock.On("GetByDay", dayOfWeek)}
}

func (_c *MockWorkingHoursRepository_GetByDay_Call) Run(run func(dayOfWeek int)) *MockWorkingHoursRepository_GetByDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockWorkingHoursRepository_GetByDay_Call) Return(_a0 *models.WorkingHours, _a1 error) *MockWorkingHoursRepository_GetByDay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkingHoursRepository_GetByDay_Call) RunAndReturn(run func(int) (*models.WorkingHours, error)) *MockWorkingHoursRepository_GetByDay_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: hours
func (_m *MockWorkingHoursRepository) Update(hours *models.WorkingHours) error {
	ret := _m.Called(hours)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.WorkingHours) error); ok {
		r0 = rf(hours)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkingHoursRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWorkingHoursRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - hours *models.WorkingHours
func (_e *MockWorkingHoursRepository_Expecter) Update(hours interface{}) *MockWorkingHoursRepository_Update_Call {
	return &MockWorkingHoursRepository_Update_Call{Call: _e.mock.On("Update", hours)}
}

func (_c *MockWorkingHoursRepository_Update_Call) Run(run func(hours *models.WorkingHours)) *MockWorkingHoursRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.WorkingHours))
	})
	return _c
}

func (_c *MockWorkingHoursRepository_Update_Call) Return(_a0 error) *MockWorkingHoursRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkingHoursRepository_Update_Call) RunAndReturn(run func(*models.WorkingHours) error) *MockWorkingHoursRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByDay provides a mock function with given fields: dayOfWeek, startTime, endTime, active
func (_m *MockWorkingHoursRepository) UpdateByDay(dayOfWeek int, startTime string, endTime string, active bool) error {
	ret := _m.Called(dayOfWeek, startTime, endTime, active)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByDay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, string, bool) error); ok {
		r0 = rf(dayOfWeek, startTime, endTime, active)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkingHoursRepository_UpdateByDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByDay'
type MockWorkingHoursRepository_UpdateByDay_Call struct {
	*mock.Call
}

// UpdateByDay is a helper method to define mock.On call
//   - dayOfWeek int
//   - startTime string
//   - endTime string
//   - active bool
func (_e *MockWorkingHoursRepository_Expecter) UpdateByDay(dayOfWeek interface{}, startTime interface{}, endTime interface{}, active interface{}) *MockWorkingHoursRepository_UpdateByDay_Call {
	return &MockWorkingHoursRepository_UpdateByDay_Call{Call: _e.mock.On("UpdateByDay", dayOfWeek, startTime, endTime, active)}
}

func (_c *MockWorkingHoursRepository_UpdateByDay_Call) Run(run func(dayOfWeek int, startTime string, endTime string, active bool)) *MockWorkingHoursRepository_UpdateByDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockWorkingHoursRepository_UpdateByDay_Call) Return(_a0 error) *MockWorkingHoursRepository_UpdateByDay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkingHoursRepository_UpdateByDay_Call) RunAndReturn(run func(int, string, string, bool) error) *MockWorkingHoursRepository_UpdateByDay_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkingHoursRepository creates a new instance of MockWorkingHoursRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkingHoursRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkingHoursRepository {
	mock := &MockWorkingHoursRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
