// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/blogem/eod-scheduler/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) Count(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockTeamRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTeamRepository_Expecter) Count(ctx interface{}) *MockTeamRepository_Count_Call {
	return &MockTeamRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockTeamRepository_Count_Call) Run(run func(ctx context.Context)) *MockTeamRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamRepository_Count_Call) Return(n int, err error) *MockTeamRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTeamRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockTeamRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) Create(ctx context.Context, member *models.TeamMember) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.TeamMember) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTeamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - member *models.TeamMember
func (_e *MockTeamRepository_Expecter) Create(ctx interface{}, member interface{}) *MockTeamRepository_Create_Call {
	return &MockTeamRepository_Create_Call{Call: _e.mock.On("Create", ctx, member)}
}

func (_c *MockTeamRepository_Create_Call) Run(run func(ctx context.Context, member *models.TeamMember)) *MockTeamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.TeamMember
		if args[1] != nil {
			arg1 = args[1].(*models.TeamMember)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_Create_Call) Return(err error) *MockTeamRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_Create_Call) RunAndReturn(run func(ctx context.Context, member *models.TeamMember) error) *MockTeamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTeamRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTeamRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTeamRepository_Delete_Call {
	return &MockTeamRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTeamRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockTeamRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_Delete_Call) Return(err error) *MockTeamRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockTeamRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveMembers provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetActiveMembers(ctx context.Context) ([]models.TeamMember, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveMembers")
	}

	var r0 []models.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.TeamMember, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.TeamMember); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetActiveMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveMembers'
type MockTeamRepository_GetActiveMembers_Call struct {
	*mock.Call
}

// GetActiveMembers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTeamRepository_Expecter) GetActiveMembers(ctx interface{}) *MockTeamRepository_GetActiveMembers_Call {
	return &MockTeamRepository_GetActiveMembers_Call{Call: _e.mock.On("GetActiveMembers", ctx)}
}

func (_c *MockTeamRepository_GetActiveMembers_Call) Run(run func(ctx context.Context)) *MockTeamRepository_GetActiveMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetActiveMembers_Call) Return(teamMembers []models.TeamMember, err error) *MockTeamRepository_GetActiveMembers_Call {
	_c.Call.Return(teamMembers, err)
	return _c
}

func (_c *MockTeamRepository_GetActiveMembers_Call) RunAndReturn(run func(ctx context.Context) ([]models.TeamMember, error)) *MockTeamRepository_GetActiveMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetAll(ctx context.Context) ([]models.TeamMember, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.TeamMember, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.TeamMember); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTeamRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTeamRepository_Expecter) GetAll(ctx interface{}) *MockTeamRepository_GetAll_Call {
	return &MockTeamRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTeamRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockTeamRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetAll_Call) Return(teamMembers []models.TeamMember, err error) *MockTeamRepository_GetAll_Call {
	_c.Call.Return(teamMembers, err)
	return _c
}

func (_c *MockTeamRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]models.TeamMember, error)) *MockTeamRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetByID(ctx context.Context, id int) (*models.TeamMember, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.TeamMember, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.TeamMember); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTeamRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTeamRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTeamRepository_GetByID_Call {
	return &MockTeamRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTeamRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockTeamRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) Return(teamMember *models.TeamMember, err error) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(teamMember, err)
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*models.TeamMember, error)) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) Update(ctx context.Context, member *models.TeamMember) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.TeamMember) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTeamRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - member *models.TeamMember
func (_e *MockTeamRepository_Expecter) Update(ctx interface{}, member interface{}) *MockTeamRepository_Update_Call {
	return &MockTeamRepository_Update_Call{Call: _e.mock.On("Update", ctx, member)}
}

func (_c *MockTeamRepository_Update_Call) Run(run func(ctx context.Context, member *models.TeamMember)) *MockTeamRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.TeamMember
		if args[1] != nil {
			arg1 = args[1].(*models.TeamMember)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_Update_Call) Return(err error) *MockTeamRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_Update_Call) RunAndReturn(run func(ctx context.Context, member *models.TeamMember) error) *MockTeamRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
